- name: Install Packstack
  hosts: pending
  vars:
   br_ex_interface: em1
   br_ex_ipaddr: "{{ ansible_default_ipv4.address }}"
   br_ex_prefix: 21  # I don't know how to get the PREFIX instead of the NETMASK
   br_ex_gateway: "{{ ansible_default_ipv4.gateway }}"

  vars_prompt:

    - name: rhn_user
      prompt: Red Hat CDN username
      private: no
    - name: rhn_password
      prompt: Red Hat CDN Password
    - name: rhn_pool_id
      prompt: Red Hat CDN Pool
      default: Employee SKU
      private: no

  tasks:

  - name: Register system into Red Hat CDN
    redhat_subscription: state=present username={{rhn_user}} password={{rhn_password}} pool={{rhn_pool_id}} autosubscribe=true

  - name: Subscribe to rhel-7-server-openstack-7.0-rpms
    shell: 'subscription-manager repos --disable="*" && subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-openstack-7.0-rpms'

  - name: Install Packstack package
    yum: name=openstack-packstack state=latest
 
  - name: Deploy Packstack all in one 
    command: packstack --allinone --os-neutron-ovs-bridge-mappings=ext-net:br-ex --os-neutron-ovs-bridge-interfaces=br-ex:{{br_ex_interface}} --nagios-install=n --os-heat-install=y --keystone-admin-passwd=redhat --keystone-demo-passwd=redhat

  - name: Set br-ex to static (br0 is dhcp by default)
    template: src=templates/ifcfg-br-ex dest=/etc/sysconfig/network-scripts/ifcfg-br-ex


  # Workaround for: https://bugzilla.redhat.com/show_bug.cgi?id=1236229 
  - name: Fix keystonerc_demo OS_IDENTITY_API_VERSION (bz 1236229)
    lineinfile: dest=/root/keystonerc_demo regexp="^export OS_IDENTITY_API_VERSION=" line="export OS_IDENTITY_API_VERSION=2.0"
  - name: Fix keystonerc_demo PS1 (bz 1236229)
    lineinfile: dest=/root/keystonerc_demo regexp="^export PS1=" line="export PS1='[\u@\h \W(keystone_demo)]\$ '"

  - name: Fix for bz 1178497
    command: systemctl mask dracut-shutdown.service

  # REMEMBER TO UNREGISTER SYSTEMS WHEN DONE!
  - name: Unregister system from Red Hat CDN
    redhat_subscription: state=absent

#  - name: Reboot
#    shell: sleep 2 && shutdown -r now "Ansible reboot"
#    async: 1
#    poll: 0
#    ignore_errors: true
  
#  - name: waiting for server to come back
#    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300