# Example of installing Packstack all in one with just one Ansible Playbook. A number of custom fixes 

- name: Install Packstack
  hosts: all
  vars:
   br_ex_ipaddr: "{{ ansible_default_ipv4.address }}"
   br_ex_prefix: 21  # I don't know how to get the PREFIX instead of the NETMASK
   br_ex_gateway: "{{ ansible_default_ipv4.gateway }}"
   rhn_org_id: YOUR_ORG_ID_NUMBER
   rhn_activationkey: YOUR_ACTIVATION_KEY

  tasks:

  - name: Register system into Red Hat CDN
    redhat_subscription: state=present org_id={{rhn_org_id}} activationkey={{rhn_activationkey}} autosubscribe=true
  
  - name: Check if OpenStack repo has already been enabled
    shell: "yum -q repolist enabled rhel-7-server-openstack-7.0-rpms|grep -w disabled"
    ignore_errors: yes
    register: disabled

  # When grep above returns 1 it means it's already enabled, so run only when grep exits with 0
  - name: Subscribe to rhel-7-server-openstack-7.0-rpms
    shell: subscription-manager repos --disable=* && subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-openstack-7.0-rpms --enable rhel-server-rhscl-7-rpms
    when: disabled.rc == 0

  - name: Install Packstack package
    yum: name=openstack-packstack state=latest

 # REMEMBER TO UNREGISTER SYSTEMS WHEN DONE!
  - name: Unregister system from Red Hat CDN
    redhat_subscription: state=absent
 
  -name: Deploy Packstack all in one 
   command: packstack --allinone --os-neutron-ovs-bridge-mappings=ext-net:br-ex --os-neutron-ovs-bridge-interfaces=br-ex:br0 --nagios-install=n --os-heat-install=y --keystone-admin-passwd=redhat --keystone-demo-passwd=redhat
 
  - name: Set br-ex to static (br0 is dhcp by default)
    template: src=templates/ifcfg-br-ex dest=/etc/sysconfig/network-scripts/ifcfg-br-ex

  - name: Fix ifcfg-br0_slave_1
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-br0_slave_1 regexp=^NAME= line=NAME=br0_slave_1
  - name: Fix ifcfg-br0_slave_2
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-br0_slave_2 regexp=^NAME= line=NAME=br0_slave_2

  - name: Fix keystonerc_demo OS_IDENTITY_API_VERSION (bz 1236229)
    lineinfile: dest=/root/keystonerc_demo regexp="^export OS_IDENTITY_API_VERSION=" line="export OS_IDENTITY_API_VERSION=2.0"
  - name: Fix keystonerc_demo PS1 (bz 1236229)
    lineinfile: dest=/root/keystonerc_demo regexp="^export PS1=" line="export PS1='[\u@\h \W(keystone_demo)]\$ '"

  - name: Fix dracut-shutdown loop (bz 1178497)
    command: systemctl mask dracut-shutdown.service

  - name: Reboot
    shell: sleep 2 && shutdown -r now "Ansible reboot"
    async: 1
    poll: 0
    ignore_errors: true
  
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
